Add reasonable limits to limits.
Kattis/problem-package-format pull request #108
Opened 2023-07-31 19:44 UTC by jsannemo

2023-07-31 20:17 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +Both of these limits must be at least 1.
```suggestion
Both of these multipliers must be at least 1.
```

2023-07-31 20:17 UTC, RagnarGrootKoerkamp approved these changes

2023-07-31 20:20 UTC, Tagl commented on spec/2023-07-draft.md
> +`output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
Looks kind of weird to start the sentence with `output`.
```suggestion
Additionally, `output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
```

2023-07-31 20:20 UTC, Tagl commented on spec/2023-07-draft.md
> +`output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
Do we want to clarify the specific case where the largest file is an empty file?
Can output be 0 in that case, thus breaking the statement about it being positive above?

2023-07-31 20:21 UTC, Tagl commented on spec/2023-07-draft.md
> +`output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
I guess that usually a custom output validator is in use when that is the case. But we do have this task: https://iceland.kattis.com/problems/iceland.flytibaka

2023-08-01 06:13 UTC, jsannemo commented on spec/2023-07-draft.md
> +`output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
Sure, but you don't *need* to lower the output limit for that problem :)

2023-08-01 06:13 UTC, jsannemo commented on spec/2023-07-draft.md
> +`output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
And anyhow, the default validator accepts for example extra spacing, right?

2023-08-01 18:19 UTC, Tagl commented on spec/2023-07-draft.md
> +`output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
That's true and yes the default validator does by default, you can switch it off.

2023-08-01 22:35 UTC, niemela requested changes
I'm not really requesting any changes, only a discussion... (i.e. change my mind 😃)

2023-08-01 22:35 UTC, niemela commented on spec/2023-07-draft.md
> +All of these limits must be positive.
This is certainly reasonable, almost *too* reasonable.

I'm generally skeptical of specifying *too* obvious things, since that implies that you can't assume any other obvious truths that are not explicitly stated. 

Also, any problem with negative limits would *always* fail, so the problem would never validate, right?

2023-08-01 22:35 UTC, niemela commented on spec/2023-07-draft.md
> +Additionally, `output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
Similar point here in that breaking this rule would just create a problem that can't be validated, which catches the issue.

Or, are we saying that validation might not be applying these limits (and it really should)? If so, this *does* add some value.

2023-08-01 22:35 UTC, niemela commented on spec/2023-07-draft.md
> +Both of these multipliers must be at least 1.
I could *almost* see a use case for `ac_to_time_limit` < 1. But it's probably a bad idea...

2023-08-02 04:46 UTC, jsannemo commented on spec/2023-07-draft.md
> +All of these limits must be positive.
Hmm, I guess I didn't really comsider fully whether `submissions/` are subject to all these limits? To me, it's not fully obvious they should be by default, since you develop problems on a different machine than running it, which is mostly fine for TL thanks to multipliers

But it is actually a good point, even though it's nice to be able to verify this without running things, since DomJudge probably won't test submissions at import time. I'm happy to remove it if you are strongly against it.

I general, the reason I want to specify this in your word "obvious" behaviour is because whenever my verifyproblem implementation *fails* I problem, I want to be able to point to where in the spec that is forbidden. I think that's reasonable. Having negative limits I at least think should be forbidden (in my judge I would reject those anyway).

2023-08-02 04:50 UTC, jsannemo commented on spec/2023-07-draft.md
> +Additionally, `output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
This was mostly a jumping board into another comment I made on slack: whether the default here should not be a fixed system default, but automatically be adjusted to e.g. max(system default, 1.5x the default output size). One could of course argue that a validation tool is allowed to just do that anyway (since "system defaults" aren't explicitly stated to be static. If you agree that this would be OK for a tool to do, I'm happy dropping this too.

2023-08-02 04:53 UTC, jsannemo commented on spec/2023-07-draft.md
> +Both of these multipliers must be at least 1.
:) but these I actually think should be specified, for the reason I stated. 

Mostly because doing allowing it to be < 1 breaks what we semantically claim `accepted` solutions do -- get Accepted, so we contradict ourselves about that.

2023-08-02 12:39 UTC, niemela commented on spec/2023-07-draft.md
> +All of these limits must be positive.
> To me, it's not fully obvious they should be by default,

No, I agree, it's not obvious.

> I'm happy to remove it if you are strongly against it.

I'm not *strongly* against it. This is a class of mistake that I'm generally scared about, based on previous experience.

> I general, the reason I want to specify this in your word "obvious" behaviour is because whenever my verifyproblem implementation _fails_ I problem, I want to be able to point to where in the spec that is forbidden. I think that's reasonable. Having negative limits I at least think should be forbidden (in my judge I would reject those anyway).

I very much agree that we want to make is so that whenever you fail validation of a problem there is a clear thing in the spec you can point to. That said, do you need this line for that? I would argue that if a problem specifies e.g. a negative memory limit you can fail it, even without running anything, because you know that it will use a least no memory, which is more than negative memory.

2023-08-02 12:43 UTC, niemela commented on spec/2023-07-draft.md
> +Additionally, `output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
I agree that it doesn't *explicitly* say that the system default is not dynamic, but if we want to allow that (and that sounds very reasonable, doesn't it?) I think we should probably mention that?

2023-08-02 12:44 UTC, niemela commented on spec/2023-07-draft.md
> +Both of these multipliers must be at least 1.
Yes, I agree. I did say *almost* :).

2023-08-02 12:52 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +Both of these multipliers must be at least 1.
We could even require them `>1`: having TL equal to slowest AC doesn't make sense. Alternatively we can add that the chosen timelimit is the first multiple of resolution strictly larger than the slowest AC.

2023-08-02 13:59 UTC, niemela commented on spec/2023-07-draft.md
> +Both of these multipliers must be at least 1.
That's also a good point.

That said, I would rather bake the > into the definition than require that `ac_to_time_limit` > 1. 

I.e. instead of:
- time limit must be >= slowest AC * `ac_to_time_limit` 
- `ac_to_time_limit` must be >1

We should say:
- time limit must be > slowest AC * `ac_to_time_limit`
- `ac_to_time_limit` must be >= 1

2023-08-02 16:00 UTC, jsannemo commented on spec/2023-07-draft.md
> +Additionally, `output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
Yes, I think it makes sense to mention.

There's still a question on whether we want to leave it to tooling to do the smart thing (i.e. set output limit to by default be > the min answer), or mandate that the "system default" will be such that it holds true. Wdyt?

2023-08-02 16:05 UTC, jsannemo commented on spec/2023-07-draft.md
> +All of these limits must be positive.
> That said, do you need this line for that?

I guess I don't *need* it. But if the layout for this spec was a bit different (i.e., when Thore's stuff is merged), it would be very natural to bake this in as part of the data type definition: "`blah`: a positive integer that ..." vs "`blah`: an integer".

2023-08-02 17:48 UTC, niemela commented on spec/2023-07-draft.md
> +Additionally, `output` may not be smaller than the largest default answer file in the problem, unless a custom output validator is used.
I think we should allow the tooling to (try to) be smart.

The intent with the "defaults" was to give a lot of freedom to systems to do "reasonable" choices. Most of the limits wont be very important in most cases anyway, and you're only supposed to set a value if you explicitly need a specific value.

2023-08-02 17:50 UTC, niemela commented on spec/2023-07-draft.md
> +All of these limits must be positive.
> But if the layout for this spec was a bit different (i.e., when Thore's stuff is merged), it would be very natural to bake this in as part of the data type definition: "`blah`: a positive integer that ..." vs "`blah`: an integer".

That's a *very* good point.

Maybe we should leave this open until *after* we merge in Thore's stuff? I am working on that...

2023-12-18 19:19 UTC, niemela commented
Closing now, let's wordsmith further (maybe reopening this PR later)?

2023-12-18 19:19 UTC, closed without merging