Invalid testcases (input and ouput validation)
Kattis/problem-package-format pull request #148
Opened 2024-01-23 08:27 UTC by thorehusfeldt

This section extends the scope of invalid _inputs_ to invalid _testcases_. It _retains_ the semantics of what a single test case input file `invalid_testcase.in` should mean (namely, that it should be rejected by at least one input validator). It _adds_ semantics for invalid outputs consistent with the rest of the specification.

The main change is to rename `data/invalid_inputs` to `data/invalid`.

2024-01-23 19:47 UTC, RagnarGrootKoerkamp commented
So to clarify, there are now two allowed patterns:
1. A single `<testcase>.in`, which should fail input validation.
2. All three of `<testcase>.{in,ans,out}`, where the `.out` should fail output validation. `<testcase>.in` must pass input validation.

Question: do we allow the second case also for `validation: default` problems? In that case we can check whether the default output validator correctly rejects some output.

2024-01-23 20:33 UTC, thorehusfeldt commented
> So to clarify, there are now two allowed patterns:

No, it’s more lenient. In particular, it is allowed to have `.ans` and `.in` (but not `.out`.)

> Question: do we allow the second case also for validation: default problems? In that case we can check whether the default output validator correctly rejects some output.

That is certainly allowed, and certainly something I’d expect to be used a lot, using exactly the above specification.

——

The above suggestion is a _minimal_ specification. We can extend with a third case. Maybe that is what you are looking for:

`.ans` exists, `.in` exist, but .`out` does _not_ exist. 

In this case. the `.in` file must _pass_ all input validators, and the output validator must _reject_ in the following invocation:
```bash
% output_validator tc.in tc.ans feedbackdir [flags] < tc.ans
```
Let me repeat that no distinction between default output validators and custom output validators is made.

I would be enthusiastic about adding this third case, but then the spec would have to talk about invocations of output validators quite early. I tried to keep the PR minimal (and still useful.)

2024-01-24 07:25 UTC, thorehusfeldt commented
If you like this presented as a table, here it is:
 
 | `.in` | `.ans` | `.out` | Meaning |
 | --- | --- | --- | --- |
 | X | | | _Invalid input_. Must fail input validation |
 | | X | | Forbidden (useless)|
 | | | X | Forbidden (useless) |
 | X | X | | Allowed, but no semantics implied. BAPCtools would answer-validate this. |
 |  | X | X | Forbidden (useless)|
 | X |  | X | Forbidden (useless)|
 |X |X |X | _Invalid output_, must fail output validation, pass input validation |
 
_Discussion_. Note that there _are_ useful semantics that _could_ be given to the cases I label “useless” (and therefore forbid them). For instance, we could say that a sole `.out` file is allowed and then should fail output validation _for all valid input files_. Mathematically, this makes sense.

But we cannot _implement_ such semantics in the current framework. For instance, we don’t have the concept of an output validator that fails _no matter what the input is_. We could have done this, for instance by adding some kind of `--input_oblivious` flag to the specification of output validators. But we haven’t done this. (We also cannot run the output validator on _all_ valid input files, because they might be difficult to generate  and there typically are too many. A compromise would be to run on all `.in` _in the repo_, but this quickly gets very messy, for instance because of flags.)

Hence I deem that none of that is worth doing and thus propose a minimally viable (and still very useful) definition above. More ambitious suggestions can certainly be made.

2024-04-08 19:39 UTC, niemela requested changes

2024-04-08 19:39 UTC, niemela commented on spec/2023-07-draft.md
> +**Invalid input.**
```suggestion
#### Invalid input

```

2024-04-08 19:39 UTC, niemela commented on spec/2023-07-draft.md
> +**Invalid output.**
```suggestion
#### Invalid output

```

2024-04-08 19:42 UTC, niemela approved these changes

2024-04-08 19:42 UTC, Tagl approved these changes

2024-04-08 19:42 UTC, merged