Define testcases
Kattis/problem-package-format pull request #153
Opened 2024-03-21 13:05 UTC by Tagl

Hopefully closes #98

2024-03-21 13:07 UTC, Tagl commented on spec/2023-07-draft.md
> +The submission's filename is passed as the first command-line argument, followed by the whitespace-separated tokens in `test.args`, if the file exists.
I do not think this is the right wording.
This is correct in the case of a single file submission and, for example, python.
In general this is not true and I think we should simply skip mentioning the first argument or say that it follows from how programs are run in general, so the main entry point is the first argument, whether it be binary, main class or main file.

2024-04-08 19:30 UTC, niemela requested changes

2024-04-08 19:30 UTC, niemela commented on spec/2023-07-draft.md
> +In other words, for any two test cases, if the contents of their `.in` and `.args` files,
```suggestion
For any two test cases, if the contents of their `.in` and `.args` files,
```

2024-04-08 19:30 UTC, niemela commented on spec/2023-07-draft.md
> +Additionally, for any two test cases, if their input,
```suggestion
This means that for any two test cases, if their input,
```

2024-04-08 19:30 UTC, niemela commented on spec/2023-07-draft.md
> +For that purpose, a judge system could choose to reuse the result of a previous run, or re-run the equivalent test case.
```suggestion
The assumption of determinism means that a judge system could choose to reuse the result of a previous run, or to re-run the equivalent test case.
```

2024-04-08 19:30 UTC, niemela commented on spec/2023-07-draft.md
> +The submission's filename is passed as the first command-line argument, followed by the whitespace-separated tokens in `test.args`, if the file exists.
That's a good point. I really don't know how to write that though... :)

2024-04-08 19:32 UTC, Tagl commented on spec/2023-07-draft.md
> +The submission's filename is passed as the first command-line argument, followed by the whitespace-separated tokens in `test.args`, if the file exists.
Will make ticket for this

2024-04-08 19:32 UTC, niemela approved these changes

2024-04-08 19:33 UTC, niemela commented
I'll merge this. @Tagl please create a ticket for the reminding issue that you brought up.

2024-04-08 19:33 UTC, merged