Verdict for scoring problems
Kattis/problem-package-format pull request #161
Opened 2024-04-10 17:07 UTC by Tagl

I based this on Thore's writeup which is linked in the issue.
Closes #110 

Verdict aggregation is no longer defined so I believe this is what we want after that change.
This means that the aggregation of the verdict is an implementation detail, whether it is first error or something else.
The only requirements are the ones stated based on whether score is aggregated using min or sum.

2024-04-10 17:28 UTC, RagnarGrootKoerkamp commented
How do `sample/` and `secret/` interact for scoring problems? I think typically the score returned by `secret/` is the one that is taken, basically ignoring `sample/`? Or we could say that by default samples give 0 points so they do not affect the overall score?

cc @thorehusfeldt

2024-04-11 12:46 UTC, Tagl commented
Yes, generally `sample` is ignored in scoring problems and an equivalent test case is placed in the appropriate place under `secret`.

2024-04-11 16:00 UTC, niemela requested changes

2024-04-11 16:00 UTC, niemela commented on spec/2023-07-draft.md
> +In most cases, the output validator could simply check whether the score is 0 and reject instead of accepting for the test case,
I'm not sure if I agree with this statement exactly. Maybe something like this?:
```suggestion
In most cases, an output validator should probably reject a test case rather than accepting and returning a score of 0,
```
It basically means the same thing...

2024-04-12 15:34 UTC, merged