Change constants from {%x%} to {{x}}; allow unrecognised names
Kattis/problem-package-format pull request #179
Opened 2024-04-14 22:09 UTC by RagnarGrootKoerkamp

Fix #176

2024-04-14 23:01 UTC, niemela requested changes

2024-04-14 23:01 UTC, niemela commented on spec/2023-07-draft.md
> +containing a name that is not defined are not modified, but may be warned for.
Start a new line after `.`.

2024-04-15 07:42 UTC, mpsijm commented on spec/2023-07-draft.md
> +containing a name that is not defined are not modified, but may be warned for.
Should there be a space after `Tags` here?

```suggestion
where `name` is one of the names defined in `constants`.
Tags `{{xyz}}` containing a name that is not defined are not modified, but may be warned for.
```

2024-04-15 12:06 UTC, niemela approved these changes

2024-04-15 12:41 UTC, merged