Allow constants longer than one character
Kattis/problem-package-format pull request #195
Opened 2024-04-19 09:16 UTC by evouga

2024-04-19 14:08 UTC, ghamerly approved these changes
Looks good to me.

2024-04-19 15:40 UTC, Tagl reviewed
Should names be allowed to start with a digit, dash, or period?

2024-04-19 15:51 UTC, niemela commented
> Should names be allowed to start with a digit, dash, or period?

...or consist only of digits? I think no. 

Maybe we want the same as for filenames?: `[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9]`

2024-04-19 16:03 UTC, Tagl commented
That would allow digits at start, I think: `[a-zA-Z_][a-zA-Z0-9_]*` would be more appropriate.

2024-04-19 20:40 UTC, niemela commented
> That would allow digits at start, 

Good point. I just copied what we have for files. Should *that* change? It feels a little bit strange that the requirements are so different?

> I think: `[a-zA-Z_][a-zA-Z0-9_]*` would be more appropriate.

That does sound better.

2024-04-23 10:30 UTC, evouga commented
No, I think it’s ok for file names to start with numbers since this is super useful for ordering test cases.

2024-04-23 10:51 UTC, niemela requested changes

2024-04-23 10:51 UTC, niemela commented on spec/2023-07-draft.md
> +Names must match the following regex: `[a-zA-Z0-9_.-]+`.
```suggestion
Names must match the following regex: `[a-zA-Z_][a-zA-Z0-9_]*`.
```

2024-04-26 07:45 UTC, niemela approved these changes

2024-04-26 07:45 UTC, merged