Draft of the scoring proposal
Kattis/problem-package-format pull request #217
Opened 2024-08-16 16:49 UTC by evouga

Here is a draft of the scoring and aggregation proposal that Fredrik and I discussed. The main points are:
 - specifying the maximum score of each test data group (rather than a problem score multiplier) in testdata.yaml
 - evenly distributing that overall score in a reasonable way to problems/subgroups by default
 - ability to specify that a group is only scored if a submission passes all test cases in a dependent group

2024-08-16 19:02 UTC, jsannemo commented
AFAICT this won't mean more config for my standard IOI style subtasks than with the previous draft wording, right?

2024-08-16 20:14 UTC, niemela commented
> AFAICT this won't mean more config for my standard IOI style subtasks than with the previous draft wording, right?

Right, that is the intent.

2024-08-16 23:56 UTC, niemela requested changes

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +For pass-fail problems, the verdict of a submission is accepted if and only if every test case in the `secret` group and its subgroups (and also in the `sample` group, unless `run_samples` is false)
```suggestion
For pass-fail problems, the verdict of a submission is accepted if and only if every test case in the `secret` group and its subgroups (and also in the `sample` group, unless `run_samples` is false) is accepted. 
Otherwise, the submission verdict is the first non-accepted verdict, where test cases are run in lexicographical order of their full file paths (note that `sample` comes before `secret` in this order).
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +In scoring problems, submissions are given a non-negative score instead of a verdict. The goal of each submission is to maximize this score. Only the `secret` group and its subgroups are scored.
```suggestion
In scoring problems, submissions are given a non-negative score instead of a verdict. 
The goal of each submission is to maximize this score. 
Only the `secret` group and its subgroups are scored.
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +Given a submission, scores are determined for test cases, test groups, and the submission itself. The scoring behavior is configured for each test data group by the following flags under `scoring` in
```suggestion
Given a submission, scores are determined for test cases, test groups, and the submission itself. 
The scoring behavior is configured for each test data group by the following flags under `scoring` in `testdata.yaml`:
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +The `secret` group, its subgroups, and every test case in these groups have a maximum possible score. The `secret` group's score may be any positive integer or `unbounded`. Subgroups of `secret` may
```suggestion
The `secret` group, its subgroups, and every test case in these groups have a maximum possible score. 
The `secret` group's score may be any positive integer or `unbounded`. 
Subgroups of `secret` may only have `unbounded` maximum score if `secret` is unbounded. 
The default value of `score` for the `secret` group is 100. 
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +where the group has `T` test cases, `A` subgroups without a provided `score`, and whose other subgroups have maximum scores that sum to `S`. It is an error if `S > M`.
```suggestion
where the group has `T` test cases, `A` subgroups without a provided `score`, and whose other subgroups have maximum scores that sum to `S`. 
It is an error if `S > M`.
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +The score of a failed test case is always 0. By default, the score of an accepted test case is its maximum score, computed as described above. A custom output validator may produce a `score.txt` file
```suggestion
The score of a failed test case is always 0. By default, the score of an accepted test case is its maximum score, computed as described above. 
A custom output validator may produce a `score.txt` file for a test case:
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +- for test cases in a group with bounded maximum score, `score.txt` must contain a single floating-point number in the range `[0,1]`. The score of the test case is this number *multiplied* by the tes
```suggestion
- for test cases in a group with bounded maximum score, `score.txt` must contain a single floating-point number in the range `[0,1]`. 
The score of the test case is this number *multiplied* by the test case maximum score.
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +- for test cases in unbounded groups, `score.txt` must contain a non-negative floating-point number. The score of the test case is that number.
```suggestion
- for test cases in unbounded groups, `score.txt` must contain a non-negative floating-point number. 
The score of the test case is that number.
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +If a group uses `pass-fail` aggregation, the group must have bounded maximum score and all subgroups must also use pass-fail aggregation. If the submission receives an accept verdict for all test cas
```suggestion
If a group uses `pass-fail` aggregation, the group must have bounded maximum score and all subgroups must also use pass-fail aggregation. 
If the submission receives an accept verdict for all test cases in the group and its subgroups, the score of the group is equal to its maximum possible score. 
Otherwise the group score is 0.
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +If a group uses `sum` aggregation, the group score is the sum of the scores of its test cases and subgroups. If a group uses `min` aggregation, then the group score is the minimum of these scores.
```suggestion
If a group uses `sum` aggregation, the group score is the sum of the scores of its test cases and subgroups. 
If a group uses `min` aggregation, then the group score is the minimum of these scores. 
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +A group may specify that it should only be scored if a submission passes all test cases in one or more other test data groups. (Otherwise, none of the group's test cases are judged and the group scor
```suggestion
A group may specify that it should only be scored if a submission passes all test cases in one or more other test data groups. 
(Otherwise, none of the group's test cases are judged and the group score is 0.) 
The paths of these required groups, relative to the `data` folder, are listed under the `require-pass` key. 
Each required group must be either `sample` or a subgroup of `secret`. 
It is an error for required groups to form cyclic dependencies or for a group to require one of its descendents.
```

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +A group may specify that it should only be scored if a submission passes all test cases in one or more other test data groups. (Otherwise, none of the group's test cases are judged and the group scor
I think it should also (or rather instead) be an error to do "forward dependencies". I.e. a group may not depend on a bibliographically later group.

2024-08-16 23:56 UTC, niemela commented on spec/2023-07-draft.md
> +The `secret` group, its subgroups, and every test case in these groups have a maximum possible score. The `secret` group's score may be any positive integer or `unbounded`. Subgroups of `secret` may
I slightly prefer `infinity` over `unbounded`.... should I?

2024-08-17 08:32 UTC, evouga commented on spec/2023-07-draft.md
> +A group may specify that it should only be scored if a submission passes all test cases in one or more other test data groups. (Otherwise, none of the group's test cases are judged and the group scor
Maybe you want the "Big" test cases to depend on the "Small"?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +For pass-fail problems, the verdict of a submission is accepted if and only if every test case in the `secret` group and its subgroups (and also in the `sample` group, unless `run_samples` is false)
```suggestion
For pass-fail problems, the verdict of a submission is accepted if and only if every test case in both the `sample` group (unless `run_samples` is `false`) and the `secret` group and its subgroups is accepted. 
```

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +For pass-fail problems, the verdict of a submission is accepted if and only if every test case in the `secret` group and its subgroups (and also in the `sample` group, unless `run_samples` is false)
`AC if and only if all accepted`: should we be more explicit re non-AC verdicts? Or be explicit that we leave that to the judge system.

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +In scoring problems, submissions are given a non-negative score instead of a verdict.
`instead of` => `as well as`?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +Given a submission, scores are determined for test cases, test groups, and the submission itself.
```suggestion
Given a submission, scores are determined for test cases, test groups, and the submission itself (which is the score of the `secret` group). 
```

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +The scoring behavior is configured for each test data group by the following flags under `scoring` in `testdata.yaml`:
clarify that `testdata.yaml` can be present in any directory under `data/`?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +| `score`       | String         | The maximum possible score of the test data group. Must be a non-negative integer or `unbounded`.
will this cause backwards incompatibility issues with old `score` and `max_score`?

Previously this was the score per testcase, now the max aggregated score, right?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +| `require-pass`| String or sequence of strings | Other test groups that a submission must pass in order to receive a score for this test group. See below.
`depends-on` or so feels more natural, but isn't quite as clear.

What does `pass`ing a testgroup mean?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +| `aggregation` | `pass-fail`, `sum`, or `min` | How the score of the test data group is determined based on the scores of the subgroups and test cases. See below.
What's the difference between `pass-fail` and `min`?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +where the group has `T` test cases, `A` subgroups without a provided `score`, and whose other subgroups have maximum scores that sum to `S`.
Explicitly say that the leftover score is equally distributed over all unscored testcases & testgroups

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +It is an error if `S > M`.
`judge error` specifically?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +If the submission receives an accept verdict for all test cases in the group and its subgroups, the score of the group is equal to its maximum possible score.
I think this is still equivalent to `min`?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +A group may specify that it should only be scored if a submission passes all test cases in one or more other test data groups.
`passes`: i.e., gets AC on all testcases in those groups and their dependencies

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +(Otherwise, none of the group's test cases are judged and the group score is 0.)
drop parens

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +It is an error for required groups to form cyclic dependencies or for a group to require one of its descendents.
can/should we impose lexicographic smaller as a restriction?

2024-08-17 10:33 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +Each required group must be either `sample` or a subgroup of `secret`.
Can we put single testcases as requirements, rather than groups?

2024-08-17 13:53 UTC, evouga commented on spec/2023-07-draft.md
> +In scoring problems, submissions are given a non-negative score instead of a verdict.
I'd rather we don't specify at all how to aggregate verdicts for scoring problems.

2024-08-17 13:54 UTC, evouga commented on spec/2023-07-draft.md
> +| `score`       | String         | The maximum possible score of the test data group. Must be a non-negative integer or `unbounded`.
Yes.

2024-08-17 13:55 UTC, evouga commented on spec/2023-07-draft.md
> +| `aggregation` | `pass-fail`, `sum`, or `min` | How the score of the test data group is determined based on the scores of the subgroups and test cases. See below.
pass-fail means you get all of the group's point if you AC every test case in the group.

2024-08-17 13:56 UTC, evouga commented on spec/2023-07-draft.md
> +It is an error for required groups to form cyclic dependencies or for a group to require one of its descendents.
You might want Big to depend on Small?

2024-08-17 13:57 UTC, evouga commented on spec/2023-07-draft.md
> +Each required group must be either `sample` or a subgroup of `secret`.
Ambivalent. How often is this wanted?

2024-08-17 13:59 UTC, evouga commented on spec/2023-07-draft.md
> +If the submission receives an accept verdict for all test cases in the group and its subgroups, the score of the group is equal to its maximum possible score.
It is equivalent to `min` with a default score.txt. But this min business is an unnatural work-around to the common case (where you want all or nothing points for a group).

2024-08-17 14:10 UTC, evouga commented
I've done a pass on your comments, @RagnarGrootKoerkamp

2024-08-17 14:50 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +Each required group must be either `sample` or a subgroup of `secret`.
Yes we want to depend on single testcases, e.g. when depending on a single sample that corresponds to each group.

2024-08-17 14:50 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +| `require-pass`| String or sequence of strings | Other test groups whose test cases a submission must AC in order to receive a score for this test group. See below.
Require the group being dependent on to be `pass-fail` or a single testcase, or `samples`, which is implicitly a `pass-fail` group (for this purpose).

2024-08-17 14:50 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +It is an error for required groups to form cyclic dependencies or for a group to require one of its descendents.
Dependencies must be alphabetical.

2024-08-17 17:12 UTC, evouga commented
@RagnarGrootKoerkamp Made the above changes

2024-08-17 17:33 UTC, RagnarGrootKoerkamp approved these changes

2024-08-17 22:16 UTC, niemela approved these changes

2024-08-17 22:24 UTC, evouga commented
This PR addresses https://github.com/Kattis/problem-package-format/issues/194 (in part), https://github.com/Kattis/problem-package-format/issues/213, https://github.com/Kattis/problem-package-format/issues/234

2024-08-17 23:31 UTC, merged