Wording & spelling fixes
Kattis/problem-package-format pull request #221
Opened 2024-08-16 20:54 UTC by eldering

2024-08-16 21:04 UTC, RagnarGrootKoerkamp approved these changes

2024-08-16 21:06 UTC, niemela requested changes

2024-08-16 21:06 UTC, niemela commented on spec/2023-07-draft.md
> +| rights_owner           | String                                                    | Value of credits, if present, otherwise value of source. | Owner of the copyright of the problem. If not present
I think this should specifically be the `authors` key of `credits`.

2024-08-16 23:34 UTC, niemela approved these changes

2024-08-16 23:37 UTC, niemela requested changes

2024-08-16 23:37 UTC, niemela commented on spec/2023-07-draft.md
> +| rights_owner           | String                                                    | Value of credits.authors, if present, otherwise value of source. | Owner of the copyright of the problem. If not
```suggestion
| rights_owner           | String                                                    | Value of `credits.authors`, if present, otherwise value of `source`. | Owner of the copyright of the problem. Required to have a value if license is something other than `unknown` or `public domain`. Forbidden if license is `public domain`.
```

2024-08-17 14:56 UTC, niemela approved these changes

2024-08-17 14:56 UTC, merged