Expectations, part 2
Kattis/problem-package-format pull request #249
Opened 2024-08-17 18:03 UTC by RagnarGrootKoerkamp

I _think_ this includes everything we discussed, but surely some subtleties are still missing.

It would be good to add some more examples, and we should also put the formal cue spec somewhere.

2024-08-17 18:48 UTC, niemela commented on spec/2023-07-draft.md
> +| time_limit_exceeded | Too slow on at least one case, and all cases are either too slow or accepted.         | Used to upper bound time limit.                           |
I still would like to allow WA, but if nobody agrees with me, so be it.

2024-08-17 18:48 UTC, niemela commented on spec/2023-07-draft.md
> +- only have verdicts present in `permitted`;
"all testcases must have verdicts from `permitted`".

2024-08-17 18:48 UTC, niemela commented on spec/2023-07-draft.md
> +- get at least one verdict in `required`;
"at least some testcase must have a verdict from `required`"

2024-08-17 18:48 UTC, niemela commented on spec/2023-07-draft.md
> +of characters is no supported.
```suggestion
of characters is not supported.
```

2024-08-17 18:48 UTC, niemela commented on spec/2023-07-draft.md
> +TODO: Did we allow `{a,b}.py` in the end?
It would be nice.

2024-08-17 18:48 UTC, niemela commented on spec/2023-07-draft.md
> +  required: [RTE, TLE]
I think this should be allowed to be `AC`.

2024-08-17 18:48 UTC, niemela commented on spec/2023-07-draft.md
> +These requirements may be too strict. To e.g. allow TLE
```suggestion
To e.g. allow TLE
```

2024-08-17 22:23 UTC, eldering commented on spec/2023-07-draft.md
> +The `score` key puts a constraint of the aggregated score of a given test group,
```suggestion
The `score` key puts a constraint on the aggregated score of a given test group,
```

2024-08-17 22:23 UTC, eldering commented on spec/2023-07-draft.md
> +| time_limit_exceeded | Too slow on at least one case, and all cases are either too slow or accepted.         | Used to upper bound time limit.                           |
```suggestion
| accepted            | Accepted as a correct solution for all test cases.                                    | At least one is required. Used to lower bound the time limit. |
| rejected            | At least one case is not accepted.                                                    |                                                           |
| wrong_answer        | At least one case is wrong answer, and all cases are either wrong answer or accepted. |                                                           |
| time_limit_exceeded | Too slow on at least one case, and all cases are either too slow or accepted.         | Used to upper bound the time limit.                       |
```

2024-08-17 22:41 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +  required: [RTE, TLE]
as discussed, we leave it as is. Tooling can suggest to move to `accepted/` instead.

2024-08-18 09:40 UTC, eldering commented on spec/2023-07-draft.md
> +`submissions` and `data/` respectively (, excluding the trailing `.in`. Wildcards (`*`) only match within a file
```suggestion
`data/` (, excluding the trailing `.in`. Wildcards (`*`) only match within a file
```

2024-08-18 09:40 UTC, eldering commented on spec/2023-07-draft.md
> +_not_ on the _set_ of test cases the group contains.
This doesn't specify how a score should be aggregated on a set of test cases (which is not exactly a test group).

2024-08-18 09:40 UTC, eldering commented on spec/2023-07-draft.md
> +normal usage.)
```suggestion
This is supported for backwards compatibility, and not recommended for normal usage.
```

2024-08-18 09:40 UTC, eldering commented on spec/2023-07-draft.md
> +requirement, instead of _replacing_ the original requirement.)
```suggestion
Note that the glob `time_limit_exceeded/*` would impose an _additional_
requirement, instead of _replacing_ the original requirement.
```

2024-08-18 09:40 UTC, eldering commented on spec/2023-07-draft.md
> +(Note that this excludes submissions that e.g. have `required: [TLE, RTE]`.)
```suggestion
Note that this excludes submissions that e.g. have `required: [TLE, RTE]`.
```

2024-08-18 09:40 UTC, eldering commented on spec/2023-07-draft.md
> +satisfies the constraints above.
```suggestion
To _opt out_ of a glob for submission(s) and optional subset of testcases from influencing the time limit, set
`use_for_time_limit: false` alongside the `permitted:` and/or `required:` keys.
Note that this means that if you want to exclude a submission completely,
then you must add `use_for_time_limit: false` to every glob that matches that submission.
```

2024-08-18 09:40 UTC, eldering commented on spec/2023-07-draft.md
> +other constraints redundant.
```suggestion
other constraints redundant and should error when it is inconsistent with other constraints.
```

2024-08-18 12:34 UTC, JoelNiemela requested changes

2024-08-18 12:34 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +| `run_time_error`      | Crashes for at least one case, and all cases either crash or are accepted.            | Used to lower bound the time limit.                           |
Shouldn't `bruteforce` be added to this table? (See "Default directories")

2024-08-18 13:31 UTC, RagnarGrootKoerkamp commented
merge?

2024-08-18 13:53 UTC, niemela approved these changes

2024-08-18 13:53 UTC, merged