First draft for static validation
Kattis/problem-package-format pull request #260
Opened 2024-08-17 22:43 UTC by Tagl

2024-08-17 23:09 UTC, evouga commented
Assuming the scoring changes get merged, `score.txt` should be in [0,1] and scales the maximum point value.

2024-08-17 23:13 UTC, JoelNiemela commented on spec/2023-07-draft.md
>    The feedbackdir must end with a path separator (typically '/' or '\\' depending on operating system),
```suggestion
  feedback_dir must end with a path separator (typically '/' or '\\' depending on operating system),
```

2024-08-17 23:13 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +When invoked the static validator will be passed at least two command line parameter.
```suggestion
When invoked, the static validator will be passed at least two command line parameters.
```

2024-08-17 23:13 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
"Submission files" might be more clear.
```suggestion
  a string specifying the absolute path to a directory containing a copy of the submission files
```

2024-08-17 23:13 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +  The feedbackdir must end with a path separator (typically '/' or '\\' depending on operating system),
```suggestion
  feedback_dir must end with a path separator (typically '/' or '\\' depending on operating system),
```

2024-08-17 23:13 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +A static validation test case is defined within a group's `testdata.yaml` file by specifying the map `static_validation`.
Doesn't this mean that there's no way to have a static validator with no flags for pass-fail problems?
(Or alternatively: doesn't this force all pass-faill static validators to have `flags` set? Which feels unnecessary.)

2024-08-17 23:14 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +When invoked the static validator will be passed at least two command line parameter.
```suggestion
When invoked the static validator will be passed at least two command line parameters.
```

2024-08-17 23:14 UTC, RagnarGrootKoerkamp commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
for single-file submissions, is this the path to the file directly? Otherwise, should we pass the entrypoint / main file?

2024-08-17 23:20 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
> for single-file submissions, is this the path to the file directly?

As I understand it, no. I also think linking directly to the file will make things more complicated for very little gain.

> Otherwise, should we pass the entrypoint / main file?

That is probably a good idea in either case?

2024-08-17 23:23 UTC, evouga commented
Do we need a submission_dir? The output validator is already required to run in a working directory containing the submitted files. We could do the same here?

2024-08-18 12:45 UTC, Tagl commented on spec/2023-07-draft.md
> +A static validation test case is defined within a group's `testdata.yaml` file by specifying the map `static_validation`.
You can specify flags as the empty string. But perhaps having an enabled: true wouldn't be bad to be clear.

2024-08-18 12:47 UTC, Tagl commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
Maybe we both pass in path to main file (code) and entrypoint (binary)?

2024-08-18 12:58 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
I don't think the binary is needed?

I think the most obvious thing to do would be to pass in `submission_dir` and `entrypoint` (which would contain the name of the mainfile/mainclass (the exact meaning is language-dependent)).

If we think the binary is needed, I think the most stable (across languages) solution is to handle that similarly to the source code: passing in `compilation_dir` and `program` (I don't think the binary is needed though?)

2024-08-18 13:05 UTC, Tagl commented
> Do we need a submission_dir? The output validator is already required to run in a working directory containing the submitted files. We could do the same here?

That's right, I have fixed this.

2024-08-18 13:08 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
Never mind — as per @evouga's comment below, `submission_dir` isn't needed.

I think `entrypoint` alone would suffice, but if not, `entrypoint` and `binary` (or something like that) would also make sense.

2024-08-18 13:10 UTC, JoelNiemela commented on spec/2023-07-draft.md
> +A static validation test case is defined within a group's `testdata.yaml` file by specifying the map `static_validation`.
Alternatively, `static_validation: true` could be used when no relevant options should be set. (I'm not sure if that is more or less ugly than having an `enabled` flag...)

2024-08-18 13:15 UTC, Tagl commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
Entrypoint in C/C++/Rust is the binary
Entrypoint in Java/Scala is the main class
Entrypoint in Python/Bash/PHP is the main code file

Are we sure entrypoint suffices?

2024-08-18 13:23 UTC, niemela commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
> Are we sure entrypoint suffices?

I think it needs the language and the entrypoint.

2024-08-18 14:58 UTC, Tagl commented on spec/2023-07-draft.md
> +  a string specifying the absolute path to a directory containing a copy of the submission
Language and entry point added instead

2024-08-18 16:18 UTC, Tagl commented on spec/2023-07-draft.md
> +A static validation test case is defined within a group's `testdata.yaml` file by specifying the map `static_validation`.
I have no strong opinion, we use shorthands in YAML in many places so just true is fine here I think.

2024-08-18 16:19 UTC, Tagl commented on spec/2023-07-draft.md
> +A static validation test case is defined within a group's `testdata.yaml` file by specifying the map `static_validation`.
Setting false would explicitly disable it then, which is essentially a no-op

2024-08-19 00:54 UTC, niemela requested changes

2024-08-19 00:54 UTC, niemela commented on spec/2023-07-draft.md
> +| static_validation      | Map or boolean                      | false                   | Not applicable | Configuration of static validation test data node. See [Static Validation](#static-validati
```suggestion
`static_validation`    | Map or boolean                      | false                   | Not applicable | Configuration of static validation test data node. See [Static Validation](#static-validation)
```

2024-08-19 01:05 UTC, niemela approved these changes

2024-08-19 01:05 UTC, merged