Require POSIX shell and Python interpreter
Kattis/problem-package-format pull request #342
Opened 2024-09-17 06:39 UTC by evouga

Clarify program requirements; addresses https://github.com/Kattis/problem-package-format/issues/330 and https://github.com/Kattis/problem-package-format/issues/341

2024-09-19 00:16 UTC, niemela requested changes

2024-09-19 00:16 UTC, niemela commented on spec/2023-07-draft.md
> +Scripts may assume a POSIX-compliant shell and that a Python 3 interpreter, C compiler, and C++ compiler are available on the system search path, aliased to `python`, `cc`, and `cpp` respectively. Co
```suggestion
Scripts may assume a POSIX-compliant shell and that a Python 3 interpreter, C compiler, and C++ compiler are available on the system search path, aliased to `python3`, `cc`, and `cpp` respectively. 
Contest systems may provide additional libraries or tools. 
Problem packages with `build` or `run` scripts are strongly encouraged to include a `README` file in the program directory documenting any such additional dependencies.
```

I think `python3` is more common than `python`? This is what you would have in a minimal(-ish) Ubuntu image, and that seems like a reasonable basis?

I'm not sure what "Contest systems may provide additional libraries or tools" really means? I would argue that dropping that line does not change the meaning at all (we are definitely not saying that everything not mentioned in the spec is forbidden), and keeping it does not make anythign more clear (at least not to me).

2024-09-19 00:16 UTC, niemela commented on spec/2023-07-draft.md
> +- a directory containing multiple Python 3 source files, two of which are `__init__.py` (defining a module) and `__main__.py` (which will be used as the program entry point);
Wait, are we *requiring* a `__init__.py`? Why should be do that?

2024-09-19 00:16 UTC, niemela commented on spec/2023-07-draft.md
> +- For submissions, ouput validators, output visualizers, and static validators: the submitted files, any compiled binaries of the submitted files and compilation byproducts, as well as any [included
...and the files in `.files`, right?

2024-09-19 00:16 UTC, niemela commented on spec/2023-07-draft.md
> +- the working directory for submissions **must not** contain any of the [test data](#test-data) files;
Except `.files`, which *must* be there.

2024-09-19 00:16 UTC, niemela commented on spec/2023-07-draft.md
> +- For submissions, ouput validators, output visualizers, and static validators: the submitted files, any compiled binaries of the submitted files and compilation byproducts, as well as any [included
What is meant by "compilation byproducts"?

2024-09-19 04:35 UTC, pehrsoderman commented on spec/2023-07-draft.md
> +- a directory containing multiple Python 3 source files, two of which are `__init__.py` (defining a module) and `__main__.py` (which will be used as the program entry point);
To ensure it is treated as a module in Python, which gives more consistency. You could also forbid it, forcing everybody to use namespace packages, but you should pick one.

2024-09-21 01:11 UTC, evouga commented on spec/2023-07-draft.md
> +- a directory containing multiple Python 3 source files, two of which are `__init__.py` (defining a module) and `__main__.py` (which will be used as the program entry point);
What's the conclusion here?

2024-09-21 01:25 UTC, evouga commented
> What is meant by "compilation byproducts"?

I've removed this clause. (But is there any case where there are some dynamic libraries, or other files produced during compilation other than the submitted files and the compiled binary, that need to be in the folder?)

2024-09-21 07:18 UTC, pehrsoderman commented on spec/2023-07-draft.md
> +- a directory containing multiple Python 3 source files, two of which are `__init__.py` (defining a module) and `__main__.py` (which will be used as the program entry point);
My opinion is that forcing the use of a `__init__.py`, which results in a regular package is more pytonic, and probably somewhat less error prone. Also, I can't imagine much use of the features of namespace packages, like including directories external to the package directory into the package. However, my opinion is not very strong. If somebody can make a good argument for using namespace packages here I am willing to listen.

2024-09-21 07:22 UTC, niemela commented
> Yes, I agree the line does not actually specify anything. However (see also the discussion at #330) in practice people will want to link against additional libraries in their `build` and `run` scripts; my intent here is to (1) explicitly acknowledge that this is allowed and (2) encourage the best practice of documenting the needed libraries in a standard place.

I would argue that that discussion actually implies the opposite (and *I* would definitely argue for the opposite). I.e. if you want an additional library it should be *included* in the package (which kinda implies that "Contest systems may *not* provide additional libraries or tools", although it's strange to say that you can't provide *additional* things, when you have not *exactly* specified what should be provided).

2024-09-21 07:30 UTC, evouga commented
> > Yes, I agree the line does not actually specify anything. However (see also the discussion at #330) in practice people will want to link against additional libraries in their `build` and `run` scripts; my intent here is to (1) explicitly acknowledge that this is allowed and (2) encourage the best practice of documenting the needed libraries in a standard place.
> 
> I would argue that that discussion actually implies the opposite (and _I_ would definitely argue for the opposite). I.e. if you want an additional library it should be _included_ in the package (which kinda implies that "Contest systems may _not_ provide additional libraries or tools", although it's strange to say that you can't provide _additional_ things, when you have not _exactly_ specified what should be provided).

There is some elegance to that approach, but as a practical matter do you *really* want individual forks of Eigen, matplotlib, libpng, etc. (and all dependencies they recursive pull in) across some fraction of your problem packages?

2024-09-21 07:45 UTC, niemela commented
> There is some elegance to that approach, but as a practical matter do you _really_ want individual forks of Eigen, matplotlib, libpng, etc. (and all dependencies they recursive pull in) across some fraction of your problem packages?

Short answer: yes.

Long answer:

I see three possible approaches:

1. systems are allowed to provide *anything*, and similarly, problem packages are allowed to depend on *anything*. Pro: this is very simple for contest runners. A problem setter need only to verify with the tech staff for the contest they are running that the packages they need are available. Con: packages (that use this) become very unportable.
2. problem packages must include whatever they depend on (but as long as they do, they can depend on anything). Pro: this is still fairly simple (but less so), *and* it is reasonably portable. Con: packages become much larger. Popular dependencies in large archive could be stored *many* times.
3. problem packages may depend on some things they don't include, but must declare this (somehow). Pro: as simple as 1 for setters (and contest runners), and (almost) as portable as 2. Con: we have to set up (and keep up to date if there isn't something we could piggyback on) some kind of registry for libraries (and versions of libraries). Given versions it's not even certain that it's that much smaller than 2 for large archives.

I think 3 is *best*, but needs to be done well, and that's hard. 1 is worst; it's fine for single contests, but terrible for reuse and archives (i.e. "distributing and sharing problems" which is the stated purpose of the format). 2 is pretty much as good as 1 for single contests, and based on what has been used *so* far wouldn't be too bad for large archives either. Also, large archvie *could* use caching to make it better if it turns out to be bad (although, not quite as easily as with 3).

So, 2 is a lot easier than 3, and almost as good.

2024-09-21 21:55 UTC, evouga commented
But Option 2 also places more burden on the package writers. "this is still fairly simple": only for header-only libraries like Eigen, though? `libpng` is probably already more annoying than package authors are realistically willing to put up with; you need its source, the source of `zlib`, and some meta-scripts that configure, build, and install both of them reliably.

And from a quick look at `matplotlib` it seems a real nightmare to build from source without `pip`, requiring things like `FreeType` in addition to a dozen Python packages.

We rejected including even just a language version string for the package programs, under the argument that (1) it's too onerous on the package authors and (2) "surely" it won't be too difficult for an archivist in 20 years to figure out how to build the problem package. This dependency-bundling seems a *lot* more effort (albeit, only for problem packages that need libraries for visualizers etc. which are a minority).

I haven't needed external libraries for problems I've written (except maybe in generators, which are outside the scope of the spec) so I don't have much of a dog in this race---I'm fine with requiring all dependencies to be bundled, if this sounds reasonable to @eldering and others in the linked issue. Though I'm skeptical authors will obey such requirements in practice.

2024-09-23 17:55 UTC, evouga commented on spec/2023-07-draft.md
> +- a directory containing multiple Python 3 source files, two of which are `__init__.py` (defining a module) and `__main__.py` (which will be used as the program entry point);
@niemela Are you ok with keeping the __init__.py requirement?

2024-09-23 18:13 UTC, niemela commented on spec/2023-07-draft.md
> +- a directory containing multiple Python 3 source files, two of which are `__init__.py` (defining a module) and `__main__.py` (which will be used as the program entry point);
Yes, I don't have a strong opinion on this. I was mostly surprised because it's a new requirement. If this seems reasonably to Python users, that I'm all for.

2025-02-21 16:31 UTC, evouga commented
What was the consensus here? Should I remove the line:
> Contest systems may provide additional libraries or tools
?

2025-02-21 17:23 UTC, niemela commented
> What was the consensus here? Should I remove the line:
> 
> > Contest systems may provide additional libraries or tools
> 
> ?

Yes. Repeating my argument from above:

> I'm not sure what "Contest systems may provide additional libraries or tools" really means? I would argue that dropping that line does not change the meaning at all (we are definitely not saying that everything not mentioned in the spec is forbidden), and keeping it does not make anythign more clear (at least not to me).

2025-02-21 18:39 UTC, niemela submitted a review, later dismissed

2025-02-21 18:39 UTC, niemela commented on spec/2023-07-draft.md
> +Contest systems may provide additional libraries or tools.
```suggestion
```

2025-02-21 18:41 UTC, niemela commented
I dropped the line:

> Contest systems may provide additional libraries or tools

At least for now. I will merge this now. If someone really want that line, please create a new PR.

2025-02-21 18:41 UTC, merged