Score revamp
Kattis/problem-package-format pull request #345
Opened 2024-09-18 22:17 UTC by evouga

Addresses https://github.com/Kattis/problem-package-format/issues/328

Also, tweaked the Maximum Score Inference section to fix what I think were some errors there---someone please double-check.

2024-09-18 23:58 UTC, niemela requested changes

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
>  Group Maximum Score | Aggregation Type     | Maximum Score of Test Case / Subgroup
The last column should probably say "Default Maximum Score ..."? It is said in the paragraph just above, but it would maybe (?) make it just a little bit more clear.

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
>  `unbounded`         | any                  | `unbounded`
It says "any" which isn't *wrong*, but `pass-fail` is not allowed if score is `unbounded`. Maybe we should change "any" to "`sum` or `min`"?

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +bounded value `M`   | `pass-fail`          | 1
In fact the maximum score does not matter in this case, but I guess 1 is as good a value as any? It might be easier to understand `aggregation` = 'pass-fail` if we don't pick a value here, but rather say that it doesn't matter?

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +where the group has `T` test cases, `A` subgroups without a provided `score`, and whose other subgroups have maximum scores that sum to `S`. This formula evenly distributes a group's leftover maximum
```suggestion
where the group has `T` test cases, `A` subgroups without a provided `score`, and whose other subgroups have maximum scores that sum to `S`. 
This formula evenly distributes a group's leftover maximum points to its test cases and subgroups with unspecified maximum score. 
It is a judge error if `S > M` for a group with bounded maximum score and `sum` aggregation.
```

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +where the group has `T` test cases, `A` subgroups without a provided `score`, and whose other subgroups have maximum scores that sum to `S`. This formula evenly distributes a group's leftover maximum
Should it also be a judge error if a subgroup maximum score is higher than the (bounded) maximum score for a group with  `min` aggregation?

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +A custom output validator may produce a `score.txt` or `unbounded_score.txt` file for a test case:
I think this fix goes the wrong way. This basically *renames* the old `score.txt` to `unbounded_score.txt` and creates a *new* file that takes the old name `score.txt`.

I think what we wanted was that `score.txt` should keep it's current semantics, i.e. it always contains the actual score, while a new file (say `score_ratio.txt`, alternatives to ratio coul be "multiplier", "factor", "relative"?) always contains a value between 0 and 1 (inclusive).

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +- for test cases in unbounded groups, `unbounded_score.txt` must contain a non-negative floating-point number.
Revert this based on above.

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +- an output validator accepts a test case in an unbounded group and does not produce an `unbounded_score.txt`;
```suggestion
- an output validator accepts a test case in an unbounded group and does not produce an `score.txt`;
```

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +- an output validator produces a `score.txt` for a test case in a group with `passs-fail` aggregation or with unbounded maximum score;
```suggestion
- an output validator produces a `score.txt` for a test case in a group with `passs-fail` aggregation;
```

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
> +- an output validator produces a `unbounded_score.txt` for a test case in a group with bounded maximum score.
```suggestion
- an output validator produces a `score_ratio.txt` for a test case in a group with unbounded maximum score.
```

2024-09-18 23:58 UTC, niemela commented on spec/2023-07-draft.md
It should also be a judge error is an output validator produces a `score.txt` outside [0, maximum] (or a `score_ratio.txt` outside [0, 1]), but I'm not sure if it should be listed *here*?

2024-09-21 01:26 UTC, evouga commented on spec/2023-07-draft.md
> +where the group has `T` test cases, `A` subgroups without a provided `score`, and whose other subgroups have maximum scores that sum to `S`. This formula evenly distributes a group's leftover maximum
Yes.

2024-09-21 02:09 UTC, evouga commented
Do we want to forbid producing `score.txt` or `score_multiplier.txt` for failed test cases? Or is to more convenient/backward-compatible to allow this (but ignore the files)?

2025-02-21 16:37 UTC, evouga commented
Are there any remaining issues with this PR?

2025-02-21 21:22 UTC, niemela commented
> Do we want to forbid producing `score.txt` or `score_multiplier.txt` for failed test cases? Or is it more convenient/backward-compatible to allow this (but ignore the files)?

That is a good question. I will move this to a new issue (that we may or may not do anything about, but we can at least discuss it) So that the rest of the changes in this PR can be merged.

2025-02-21 21:23 UTC, merged