Schemas for problem.yaml, testdata.yaml
Kattis/problem-package-format pull request #45
Opened 2023-07-22 06:12 UTC by thorehusfeldt

Add formal specifications for
* `problem.yaml` in [spec/schemas/problem.cue](https://github.com/Kattis/problem-package-format/compare/master...thorehusfeldt:problem-package-format:master#diff-bb0250814460bc90e45e4bfd930df57fa5037546e079cc344ea49e393f6b6856)  
*  `testdata.yaml` in [spec/schemas/testdata_settings.cue](https://github.com/Kattis/problem-package-format/compare/master...thorehusfeldt:problem-package-format:master#diff-37015d52e0429546558e36cfde5c9020e2bc2070f2afb2fb0ac318157fc2ce28)

Notable changes after working group meeting 21 Jul 2023 (Lund):
1. made `""` the default for `validator_flags` (consistent with other flags)
2. made `*"all"` the default for `languages`, note that `string` is _not_ an option (but `[...string]` is).
3. the type for `time_multiplier` and `time_safety_margin` is now “nonnnegative number”
4. the `range` keys are checked for internal consistency

Things to discuss:
1. `input_validator_flags` may change to `input_validators`.
2. should there be a fixed regex for numbers? (Because we may want to think about `005.15` or `1e-15`.)

2023-07-22 09:38 UTC, RagnarGrootKoerkamp commented
discussion notes:

```
problem.yaml:
- validator_flags

PROPOSAL:

testdata.yaml
- input_validator_flags: <flags>
- input_validator_flags:
  <name>: <flags>
  syntax.ctd: --skip
- output_validator_flags

NOTES:
- deprecate validator_flags from problem.yaml
- only allow a single output validator
- input_validator_flags: <flags> means flags for all validators
- input_validator_flags: <dict> specifies flags for some validators, but all are run anyway
- output_validator_flags: <flags> specifies flags for the single output validator
- output_validator_flags: <dict> is *not allowed*

What about testdata.yaml inheritance?
- Update the spec to explicitly say: if testdata.yaml is not present in a directory=testgroup, inherit it from the closest ancestor
- ICPC spec: only testdata.yaml in data/, with only allowed key being output_validator_flags
```

2023-07-22 17:59 UTC, thorehusfeldt commented
This pull request addresses issue #30

2023-07-23 16:45 UTC, jsannemo commented on spec/schemas/problem.cue
> +    problem_format_version?: *"legacy" | "draft" | =~ "\d\d\d\d-\d\d(-draft)?"
Pessimistic assumption that the spec won't be updated in e.g. the year 10323.

2023-07-24 08:41 UTC, niemela requested changes

2023-07-24 08:41 UTC, niemela commented on spec/schemas/problem.cue
> +        interaction?: *false | true
```suggestion
        interactive?: *false | true
```

2023-07-24 08:41 UTC, niemela commented on spec/schemas/problem.cue
> +        scoring?: *false | true
I wonder how often there is a problem with `type = scoring` and a validator that is *not*.  @jsannemo do you know of any such examples?

2023-07-24 09:34 UTC, simonlindholm commented on spec/schemas/problem.cue
> +        scoring?: *false | true
Most of our problems that use output validators are of that kind. EGOI carnivalgenerals, bikesvscars and sopsug, for instance.

2023-07-24 11:03 UTC, niemela commented on spec/schemas/problem.cue
> +        scoring?: *false | true
Ah, well then, never mind...

2023-07-25 07:54 UTC, thorehusfeldt commented on spec/schemas/problem.cue
> +    problem_format_version?: *"legacy" | "draft" | =~ "\d\d\d\d-\d\d(-draft)?"
Changed to ` =~"[0-9-]+(-draft)?"`

2023-07-25 07:56 UTC, niemela commented on spec/schemas/problem.cue
> +    problem_format_version?: *"legacy" | "draft" | =~ "\d\d\d\d-\d\d(-draft)?"
Not very important, but that just seems less precise.

I'll rather make an update when needed (in 7976 years).

2023-07-25 07:58 UTC, thorehusfeldt commented
(I think all of @niemela ’s change requests were addressed and resolved, yet the “Changes requested” warning remains red. Maybe only FN can approve this? I’m asking him to re-review.)

2023-07-25 08:07 UTC, niemela approved these changes
I'm fine with this as is, but see comments...

2023-07-25 08:07 UTC, niemela commented on spec/schemas/problem_package.cue
> +	validation?: *"default" | "custom" | {["multipass" | "interactive" | "scoring"]: *false | true}
Isn't this a little bit strange, now when all the keys are just bools?

What I mean is that we say `custom` (which is obviously "equivalent" to `custom: true`), but we do say `multipass: true`.

2023-07-25 08:07 UTC, niemela commented on spec/schemas/problem_package.cue
> +	problem_format_version?: *"legacy" | "draft" | =~"[0-9-]+(-draft)?"
I think `[0-9-]+(-draft)?` is less good than `\d\d\d\d-\d\d(-draft)?`. The latter more precisely specifies what we actually expect.

Also, I think we (including me) are overthinking this. We don't *have* properly support any future name now, we can change this if we realize in the future that we want to allow more. But right *now* we are thinking that all version names will be `legacy`, `draft`, or `\d\d\d\d-\d\d(-draft)?`, so I think we should say that.

2023-07-25 08:23 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	validation?: *"default" | "custom" | {["multipass" | "interactive" | "scoring"]: *false | true}
I have no strong opinion on this and welcome alternatives. 

## what we have

Here are some things you can do with the above:
```yaml
validation: "default" # probably seldom used, because it's default
validation: "custom"
validation:
    multiplass: true
validation:
    interactive: true
    scoring: true
    multipass: true
```
This makes sense to me. 

## alternative 1
However, an alternative is:
```cue
custom-validation: { 
    custom : true
     [ "multipass" | "interactive" | "scoring"]: *false | true  
```
Then the above would become:
```yaml
# no way to explicitly say "validation: default"
costum-validation:
    custom: true
validation:
    custom: true
    multiplass: true
custom-validation:
    custom: true
    interactive: true
    scoring: true
    multipass: true
```
This is  very explicit but feels verbose

## alternative 2
However, an alternative is:
```cue
use-default-output-validator?: *true | false
if use-default-output-validator == false:
    custom-validation?: {  [ "multipass" | "interactive" | "scoring"]: *false | true  
```
Then the above would become:
```yaml
use-default-output-validator: false
use-default-output-validator: true

custom-validation:
    multipass: true

use-default-output-validator: true # redundant, but ok to specify
custom-custom-validation:
    interactive: true
    scoring: true
    multipass: true
```

I have no strong opinion about these.

2023-07-25 09:21 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	problem_format_version?: *"legacy" | "draft" | =~"^[0-9]{4}-[0-2][0-9](-draft)?$"
If @jsannemo insists, this can become `^[0-9]+-` etc.

2023-07-25 09:29 UTC, niemela commented on spec/schemas/problem_package.cue
> +	validation?: *"default" | "custom" | {["multipass" | "interactive" | "scoring"]: *false | true}
I think "what we have" is pretty good. Minor clarification request though. I think all of these are legal, right?:
```yaml
validation: default # probably seldom used, because it's default
validation: custom
validation:
    multipass: true
validation:multipass: true
validation:
    interactive: true
    scoring: true
    multipass: true
```

I don't like "alternative 1" as much:
- allowing explicit `validation: default` is nice (but not very important)
- `custom: true` is implied by any other value being true, but if I understand correctly you're not required to always set `custom: true` (nor are you forbidden from doing it).
- You're not actually suggesting that they key should be called `custom-validation`, right?

I don't understand what your "alternative 2" suggestion is. Why are there 3 different keys (`use-default-output-validator`, `custom-validation`, `custom-custom-validation`)?

2023-07-25 09:31 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +		// if license =~ "unknown" {  numexists(>=1, rights_owner, author, source) }
This would be nice to specify, but isn’t worth it in CUE 0.5.0 because `numexists` is not implemented (and the workarounds very verbose.)

2023-07-25 09:31 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	}
From the perspective of the ICPC subset, this is not optimal. A cleaner (but more verbose) version is:

```cue
custom-validation?: {
  custom: false | true
  interactive?: *false | true
  ...
}
```
but it’s not clear to me what the defaults or optionality should be.

2023-07-25 09:31 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	type?:       *"pass-fail" | "scoring"
Note that the key `type` is _forbidden_ in the `icpc` subset if we do it like this.

2023-07-25 09:31 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
`verdict` is not a good name. Even `mode` is better. For symmetry, consider `score-aggregation` and `verdict-aggregation`.

2023-07-25 09:31 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
>  		score?: number
This is now a one-key optional field, which seems structurally unnecessary.

2023-07-25 09:31 UTC, RagnarGrootKoerkamp commented
If we only allow bools (and not `multipass: 2`), I think passing a list (set) of flags is simple:
```
validation: default
validation: custom
validation: interactive
validation: multipass
validation: [scoring, interactive, multipass]
```

side question: how does `validation: scoring` interact with `type: scoring`? Does one imply the other? Is one of the two redundant?

2023-07-25 09:33 UTC, niemela commented on spec/schemas/problem_package.cue
> +	problem_format_version?: *"legacy" | "draft" | =~"^[0-9]{4}-[0-2][0-9](-draft)?$"
Super duper nitpick; why `...[0-2]...`? There are only 12 months? I would understand either `...[0-1]...`, or `...[0-9]...`.

(And I think I would prefer `^[0-9]{4}-[0-9]{2}(-draft)?$`.)

2023-07-25 09:35 UTC, niemela commented on spec/schemas/problem_package.cue
> +	}
I think it's fine. The ICPC subset *does* live in the reality that it is a subset of a greater whole.

2023-07-25 09:38 UTC, RagnarGrootKoerkamp commented on spec/schemas/problem_package.cue
> +	validation?: *"default" | "custom" | {["multipass" | "interactive" | "scoring"]: *false | true}
`validation:multipass: true` this is not valid yaml sadly

2023-07-25 09:38 UTC, Tagl commented
> side question: how does `validation: scoring` interact with `type: scoring`? Does one imply the other? Is one of the two redundant?

Scoring in validation implies the output validator also returns a custom score for each testcase, which can then be used by the score aggregation method. The default score is 1. Scoring in type states that the problem is not pass-fail.

2023-07-25 09:39 UTC, thorehusfeldt commented
Let’s make “what should `validation` be a separate issue.

`validation: scoring` means “there is a cusom output validator and it produces `score.txt`.

OTOH, `type:scoring` works fine with the default output validator (in fact, that setup accounts for most of the problems I know), but means “the default _grader_ should aggregate scores”. (The scores can be `1` for every `AC`, and please sum them. That’s the current default if you say nothing else.)

But `validation: scoring` makes no sense without `type: scoring`.
——

I’d be happy to reduce some of this redundancy and conceptual overlap.

2023-07-25 09:41 UTC, niemela commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
Could you elaborate on why `verdict` is not good?

I don't really like `mode`, because as you are alluding both `aggregation`, and `verdict` describes different modes of operation. I kinda like `score-aggregation` and `verdict-aggregation` t.b.h.. @jsannemo is it too long?

(Maybe `score-agg` and `verdict-agg`? I'm only 80% joking).

2023-07-25 09:41 UTC, niemela commented on spec/schemas/problem_package.cue
>  		score?: number
I don't understand, can you explain?

2023-07-25 09:50 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
A `verdict` to me should be something like `AC` or `WA`, not “how is the verdict computed”, which should be `verdict-policy` or something like that.

But it’s a rare enough key that I don’t want to make a fuss about this. (It’s possible that it will _never_ appear in any yaml ever, because of the sensible defaults.)

2023-07-25 09:51 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
>  		score?: number
We now have
```yaml
grading:
    score: 45
max_score: 54
```
If `grading` can never have any other subkey, we might as well say
```yaml
score: 45
max_score: 54
```

2023-07-25 09:53 UTC, niemela commented on spec/schemas/problem_package.cue
> +	validation?: *"default" | "custom" | {["multipass" | "interactive" | "scoring"]: *false | true}
> `validation:multipass: true` is not valid yaml sadly

Really? 😞 The random YAML validator I found online accepted it.

2023-07-25 09:58 UTC, niemela commented on spec/schemas/problem_package.cue
>  		score?: number
> If `grading` can never have any other subkey, we might as well say

*If*, sure, but it *can* have `max_score`, `aggregation`, and `verdict`. I feel I'm missing something here?

2023-07-25 10:05 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	type?:       *"pass-fail" | "scoring"
For [reasons], I cannot specify a schema extension that removes an earlier restriction on a key. 

Whatever conforms to `-full` must also conform to `-icpc`, otherwise the latter is not extension. (Extensions can allow _more keys_ but cannot _undo restrictions on “inherited” keys_.)

So what one _can_ do is add new keys. So `-full` can have a `type: "pass-fail" | "scoring"` (or better, a `scoring: *false | true` field) that `-icpc` lacks.

All of this would go away if a problem could say “I want to be understood as an ICPC-compliant problem.”. For instance by specifying that in the versions string or adding a `subversions` field or a `icpc: boolean` field. There was no consensus about those proposals.

2023-07-25 10:59 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
> But if it's rare then it should be fine to make it longer?

Wow. Actually a great argument.

2023-07-25 11:01 UTC, thorehusfeldt commented on spec/schemas/problem_package.cue
> +	validation?: *"default" | "custom" | {["multipass" | "interactive" | "scoring"]: *false | true}
Is
```yaml
validation: { multipass: true }
```
valid?

2023-07-25 11:02 UTC, RagnarGrootKoerkamp commented on spec/schemas/problem_package.cue
> +	validation?: *"default" | "custom" | {["multipass" | "interactive" | "scoring"]: *false | true}
yes, that works

2023-07-25 11:03 UTC, RagnarGrootKoerkamp commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
> It’s possible that it will never appear in any yaml ever, because of the sensible defaults

is it rare enough to drop?

2023-07-25 11:05 UTC, niemela commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
> is it rare enough to drop?

No, I don't think so. It is in fact used some.

2023-07-25 11:11 UTC, eldering commented on spec/schemas/problem_package.cue
> +	type?:       *"pass-fail" | "scoring"
Let's not let the restrictions of CUE prevent us from doing what we think is best.

I'd opt (as I understand with Fredrik) for making `type: pass-fail` an optional key/value in the ICPC subset. I'm fine that in the CUE specification this then allows any other value as well, or some other minor difference from what we intend.

2023-07-25 11:12 UTC, thorehusfeldt commented
Let me make another pitch for allowing `problem.yaml` to explicitly signal “I am an ICPC-conformal problem.”

_How_ this is signalled is not important,  but for instance `version: "2023-07-icpc-draft"` is one way. If we have that then we can always allow the optional `type` field in `problem.yaml`, but also restrict its values like this:

```cue
type?: *"pass-fail" | "scoring"
if version =~ "icpc": { type?: "pass-fail" }
```

Thus, a `problem.yaml` for an ICPC-problem _can_ specify its version, _can_ in that version string include `icpc`, and _can_ be explicit about `type: "icpc"`. But tooling _can_ infer the default value of the optional `type` field as `pass-fail`. 

The only thing that is forbidden is an explicit `type: scoring` when `version` matches `icpc`. Exactly what we want.

Other problems can be `pass-fail` _without_ also promising `icpc`. On the other hand, `icpc` would forbid many of the `-full` fields (such as some `validation` keys, `languages`, etc.)

To me, this exactly what we want. Explicit, clear, readable, no overhead. Easier to write tooling, easier to communicate among humans.

2023-07-25 15:14 UTC, jsannemo commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
I expect it to be used ~0 times (the defaults are chosen to be compliant with the normal IOI scoring), so feel free making it a UUID or something other absurd thing.

2023-07-25 15:17 UTC, niemela commented on spec/schemas/problem_package.cue
> +	verdict:               "first_error" | "accept_if_any_accepted"
Ok, I think an UUID would be worse than necessary, but we could absolutely do `score-aggregation` and `verdict-aggregation` then?

2023-07-25 15:38 UTC, RagnarGrootKoerkamp commented on spec/schemas/problem_package.cue
>  		score?: number
The point is that the only allowed key in `grading:` is `score:`, so we may as well drop the nesting and directly put `score:` into the surrounding scope, which indeed makes sense to me.

2023-07-25 18:03 UTC, niemela commented on spec/schemas/problem_package.cue
>  		score?: number
Exactly the current structure according to the spec is:

```yaml
grading:
  score: 1
  max_score: 100
  aggregation: sum
  verdict: first_error
input_validator_flags: none
output_validator_flags: none
```

So removing `grading` because `score` is the only thing in there is just wrong. OTOH, we *could* remove `grading` because there are only a total of 6 keys, do we really need two levels? If so, we would get:

```yaml
score: 1
max_score: 100
aggregation: sum
verdict: first_error
input_validator_flags: none
output_validator_flags: none
```

I honestly don't know which one I prefer...

2023-07-25 18:11 UTC, jsannemo commented
I like that all grading things are in one subkey. It also makes it only a
single key that "really" should be ignored by the ICPC subset (both input
and output validator flags makes sense to keep IMO).

On Tue, 25 Jul 2023, 20:03 Fredrik Niemelä, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In spec/schemas/problem_package.cue
> <https://github.com/Kattis/problem-package-format/pull/45#discussion_r1273906964>
> :
>
> >  }
>
>  #testdata_settings: {
> +	#testdata_settings_icpc
>  	grading?:
>  		score?: number
>
> Exactly the current structure according to the spec is:
>
> grading:
>   score: 1
>   max_score: 100
>   aggregation: sum
>   verdict: first_errorinput_validator_flags: noneoutput_validator_flags: none
>
> So removing grading because score is the only thing in there is just
> wrong. OTOH, we *could* remove grading because there are only a total of
> 6 keys, do we really need two levels? If so, we would get:
>
> score: 1max_score: 100aggregation: sumverdict: first_errorinput_validator_flags: noneoutput_validator_flags: none
>
> I honestly don't know which one I prefer...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Kattis/problem-package-format/pull/45#discussion_r1273906964>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHIMXOSO3CK3U6KNDRAJRDXSAC6NANCNFSM6AAAAAA2TUIS7Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-25 18:12 UTC, niemela commented
> I like that all grading things are in one subkey. It also makes it only a single key that "really" should be ignored by the ICPC subset (both input and output validator flags makes sense to keep IMO).

Yes, those are (at least) two good points.

2023-07-25 19:17 UTC, thorehusfeldt commented
Something else that happened is that `examples/problem_settings` contains a half a dozen `problem.yaml` examples, see [https://github.com/thorehusfeldt/problem-package-format/tree/master/examples/problem_settings](https://github.com/thorehusfeldt/problem-package-format/tree/master/examples/problem_settings). These are automatically checked against the schema by running

```sh
bash test.sh
```

in [https://github.com/thorehusfeldt/problem-package-format/blob/master/spec/schemas/test.sh](https://github.com/thorehusfeldt/problem-package-format/blob/master/spec/schemas/test.sh), provided you have `cue` installed.

2023-07-27 08:15 UTC, thorehusfeldt commented
Allow me to draw you attention to `examples/problem_icpc.yaml`, which contains a bunch of icpc-valid `problem.yaml`:

```yaml
# Minimal
name: Hello World!
---
# Typical
name: Hello World!
license: cc by-sa
author: Alice McAuthorson
---
# Can set type, but it's redundant
name: Hello World!
type: pass-fail
---
# Use all available fields
name: 
  en: Maximally Specified ICPC Problem
  de: Maksimal spezifiziertes ICPC-Problem
problem_format_version: 2023-07
type: pass-fail
author: Maxine Maximus
source: MCPC 2023
source_url: http://maximal-contest.2023.com
license: cc by-sa
rights_owner: Momma Maximus
limits:
  time_multiplier: 
    ac_to_time_limit: 3.0
    time_limit_to_tle: 1.4
  time_limit: 1
  time_resolution: .5
  memory: 1024
  validation_time: 21
validation:
  interactive: true
keywords: [greedy, interactive, needs big integers]
constants:
  max_n: 1000
  bases: ACTG
```
A similar file (for the full spec) is in `examples/problem_full.yaml`. This gives you a good overview of where the syntax is by now. (All of these validate, see `schema/test.sh`.)

You can add more examples if you find that instructive. I’ll make a long file of rejected examples _real soon now_.

2023-07-27 09:49 UTC, thorehusfeldt commented
# Ready to merge

I think this PR is ready to be merged; I can’t really improve this much.

What’s new in this branch:

## YAML examples

Three commented YAML files are in https://github.com/thorehusfeldt/problem-package-format/tree/master/examples:

1. [`problem_icpc.yaml` ](https://github.com/thorehusfeldt/problem-package-format/blob/master/examples/problem_full.yaml) contains a handful of example `problem.yaml` for the ICPC subset
2. [`problem_full.yaml`](https://github.com/thorehusfeldt/problem-package-format/blob/master/examples/problem_icpc.yaml) contains a handful of example `problem.yaml` for the full specification (but not in the ICPC subset)
3. [problem_invalid.yaml](https://github.com/thorehusfeldt/problem-package-format/blob/master/examples/problem_invalid.yaml)  contains commented examples of invalid `problem.yaml`.


## CUE schema

The main contribution is a schema in https://github.com/thorehusfeldt/problem-package-format/blob/master/spec/schemas/problem_package.cue using the [CUE language](https://cuelang.org). 

It’s a concise and human-readable way to solidify our specification. Moreover, with cue installed, you can run

```bash
cue vet problem.yaml problem_package.cue
```
to “vet” (=validate) a `problem.yaml` file against the schema. 

You can restrict to the ICPC subset like this:
```bash
cue vet problem.yaml problem_package.cue -d "#icpc"
```

You can also validate testdata settings:
```bash
cue vet testdata.yaml problem_package.cue -d "#testdata_settings"
```

## Testing

The bash script [test.sh](https://github.com/thorehusfeldt/problem-package-format/blob/master/spec/schemas/test.sh) tests that indeed the examples behave as they should against the CUE specification.

2023-07-27 20:29 UTC, jsannemo commented
"# Typical" should probably include the problem format version (since it's otherwise a legacy problem.yaml).

2023-07-28 10:33 UTC, RagnarGrootKoerkamp approved these changes

2023-07-28 10:33 UTC, RagnarGrootKoerkamp commented on spec/schemas/test.sh
> +output_dir="tmp"
You could use `mktemp -d` instead to get an actual temporary directory, and delete it again at the end of the script

2023-07-28 10:33 UTC, RagnarGrootKoerkamp commented on spec/schemas/test.sh
> +	}' ../../examples/problem_full.yaml
hrmm; so I take it `cue` can't reject the individual parts of a multipart yaml file? unfortunate but somewhat inevitable.

2023-07-28 10:33 UTC, RagnarGrootKoerkamp commented on spec/schemas/test.sh
> +cue vet ../../examples/problem_full.yaml problem_package.cue
We could add github CI to run this in some docker container with cue installed on every PR/commit to master.

2023-07-28 10:33 UTC, RagnarGrootKoerkamp commented on examples/problem_full.yaml
> +# All of these validate against the schema
We could replace the example `problem.yaml` files with these files, ideally by including them using a liquid template or so. I can figure that out as a follow up.

2023-07-28 11:21 UTC, thorehusfeldt commented on spec/schemas/test.sh
> +output_dir="tmp"
I actually found it _more_ useful to have those files around for debugging. Ideally this would be flag. No strong opinion.

2023-07-28 11:22 UTC, thorehusfeldt commented on spec/schemas/test.sh
> +	}' ../../examples/problem_full.yaml
Right now, the `cue vet` CLI bails at first error. It’s not part of the CUE spec, but an implementation detail of tooling.

2023-07-28 11:26 UTC, thorehusfeldt commented on examples/problem_full.yaml
> +# All of these validate against the schema
If you want to see where I want the documentation to go, check out https://problem-package-format-copy.readthedocs.io/en/latest/. Ideally, all directives like

```
.. code-block :: yaml
   bla
```

should be extracted by `test.sh` and validated against the schema. But this uses RTD, not markown; it could open up for

```
.. code-block :: yaml
    :schema: #icpc
   bla
```

I think of this as nice-to-have, low-priority.

2023-07-28 11:47 UTC, RagnarGrootKoerkamp commented on examples/problem_full.yaml
> +# All of these validate against the schema
side note: I saw that readthedocs can also support markdown with some plugins. That would be nice, if it can produce the same structured text as the `rst` sources

2023-07-28 12:24 UTC, RagnarGrootKoerkamp commented on examples/problem_full.yaml
> +# All of these validate against the schema
Oh, also just found this:
https://ccs-specs.icpc.io/
build as
https://github.com/icpc/ccs-specs/blob/gh-pages/dev-notes.md

2023-07-28 15:25 UTC, thorehusfeldt commented on examples/problem_full.yaml
> +# All of these validate against the schema
By the way, 
```rst
.. literalinclude:: path/to/problem.yaml
  :language: yaml
```
works out of the box with RST.

I’ll make a complete, small example problem in my fork whose various files are included in the documentation just so show this off. (Then CI could `verifyproblem` the problem and `cue` all the `yaml`. The sky is the limit.)

2023-07-28 15:58 UTC, thorehusfeldt commented on examples/problem_full.yaml
> +# All of these validate against the schema
OK, here you go. At [https://problem-package-format-copy.readthedocs.io/en/latest/core.html#problem-settings](https://problem-package-format-copy.readthedocs.io/en/latest/core.html#problem-settings) I include the file `increment/problem.yaml`, which is an example (toy but complete) problem in https://github.com/thorehusfeldt/problem_package_format_copy/tree/main/problems/increment . Theoretically, `increment` can be validated by `verifyproblem`. All of its files can be included in the documentation.

We should also have a scoring problem under `problems` and use that to illustrate the more advanced part of the specification.

2023-09-19 18:20 UTC, niemela commented
@thorehusfeldt How correct are this schemas still (considering all the changes that have happened since the PR was created)?

I think we all agree that having schemas is an obvious good. So my question is only should we merge this now, either because it's perfectly in line with the spec as it stands right now, or because it's close enough and we can fix it in a follow up PR?

2023-09-20 06:48 UTC, thorehusfeldt commented
The schemas in my own for are up-to-date, as far as I’ve been able to follow.

[https://github.com/thorehusfeldt/problem_package_format_copy/tree/main/support](https://github.com/thorehusfeldt/problem_package_format_copy/tree/main/support)

Moreover, the script at [https://github.com/thorehusfeldt/problem_package_format_copy/blob/main/test.sh](https://github.com/thorehusfeldt/problem_package_format_copy/blob/main/test.sh) runs every yaml file in my fork (in particular all the yaml files appearing in the documentation) against those schemas, to the documentation and the schema specification are _in agreement_. 

At BAPCtools, we’ve taking this to one more level; the `generators.yaml` framework not only as a validating CUE schema, but
1. the script that checks internal validity is run by Github’s  continuous integration framework, so validity is ensured on commit
2. we have translated the CUE schema also into a JSON schema
3. the JSON schema (and a full test suite) is published at the schema repository schemastore.org, so for every user on the planet that uses a compliant  editor (such as VS Code), there is now out-of-the-box syntax checking, autocompletion, and hints for writing problem package generators without any configuration necessary. It feels like complete science-fiction. (In VIM and Emacs you have to set this up, but it takes a few minutes.)

We can easily do something similar for `problem.yaml` and `testdata.yaml`.

2023-09-20 17:50 UTC, niemela commented
> The schemas in my own fork are up-to-date, as far as I’ve been able to follow.

Are you saying that this PR is, not not?

2023-09-22 08:32 UTC, thorehusfeldt commented
Requires some updates. I’ll close this PR and make a new one on a feature branch.

2023-09-22 08:32 UTC, closed without merging